export const Employees = [
  {
    _id: "1",
    username: "John Doe",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Software Engineer",
    Team: "ABC",
    scores: [4, 5, 3, 2],
  },
  {
    _id: "2",
    username: "Jane Smith",
    testStatus: "In Progress",
    role: "Prospect",
    JobTitle: "Marketing Specialist",
    Team: "HT",
    scores: [4, 5, 3, 2],
  },
  {
    _id: "3",
    username: "Alice Johnson",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Project Manager",
    Team: "XYZ",
    scores: [7, 6, 5, 3],
  },
  {
    _id: "4",
    username: "Robert Brown",
    testStatus: "Not Completed",
    role: "Prospect",
    JobTitle: "Sales Associate",
    Team: "XYZ",
    scores: [7, 3, 7, 4],
  },
  {
    _id: "5",
    username: "Emily Davis",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "HR Coordinator",
    Team: "ABC",
    scores: [3, 6, 7, 3],
  },
  {
    _id: "6",
    username: "Michael Wilson",
    testStatus: "Not Completed",
    role: "Prospect",
    JobTitle: "Data Analyst",
    Team: "ABC",
    scores: [2, 7, 7, 2],
  },
  {
    _id: "7",
    username: "Sophia Martinez",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Graphic Designer",
    Team: "HT",
    scores: [6, 8, 5, 7],
  },
  {
    _id: "8",
    username: "Liam Taylor",
    testStatus: "In Progress",
    role: "Prospect",
    JobTitle: "Software Tester",
    Team: "XYZ",
    scores: [5, 6, 4, 3],
  },
  {
    _id: "9",
    username: "Olivia Anderson",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Finance Manager",
    Team: "ABC",
    scores: [9, 8, 7, 6],
  },
  {
    _id: "10",
    username: "Ethan Thomas",
    testStatus: "Not Completed",
    role: "Prospect",
    JobTitle: "Customer Service Rep",
    Team: "HT",
    scores: [3, 4, 5, 3],
  },
  {
    _id: "11",
    username: "Ava Harris",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Content Writer",
    Team: "XYZ",
    scores: [8, 7, 6, 5],
  },
  {
    _id: "12",
    username: "Noah Clark",
    testStatus: "In Progress",
    role: "Prospect",
    JobTitle: "DevOps Engineer",
    Team: "ABC",
    scores: [5, 6, 5, 4],
  },
  {
    _id: "13",
    username: "Emma Lewis",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Operations Manager",
    Team: "HT",
    scores: [6, 7, 8, 9],
  },
  {
    _id: "14",
    username: "Lucas Walker",
    testStatus: "Not Completed",
    role: "Prospect",
    JobTitle: "UX Designer",
    Team: "XYZ",
    scores: [4, 3, 5, 4],
  },
  {
    _id: "15",
    username: "Isabella Young",
    testStatus: "Completed",
    role: "Employee",
    JobTitle: "Legal Advisor",
    Team: "ABC",
    scores: [7, 8, 7, 8],
  },
];
